import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import { OAuth2Client } from 'google-auth-library';
import User from '../models/User'; import { tokenFor } from '../utils/jwt'; import type { AuthenticatedRequest } from '../types/auth';
import { loginSchema, passwordSchema, registerSchema } from '../validators/authValidator';

const cookieOptions={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,maxAge:7*24*60*60*1000};
const publicUser=(u:any)=>({id:u._id.toString(),name:u.name,email:u.email,avatar:u.avatar||'',createdAt:u.createdAt});
const setAuthCookie=(res:Response,id:string)=>res.cookie('token',tokenFor(id),cookieOptions);

export async function register(req:Request,res:Response){try{const parsed=registerSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,message:'Invalid registration data',errors:parsed.error.issues});const {name,email,password}=parsed.data;const normalized=email.toLowerCase();if(await User.exists({email:normalized}))return res.status(409).json({success:false,message:'An account with this email already exists'});const hash=await bcrypt.hash(password,12);const user=await User.create({name,email:normalized,password:hash});setAuthCookie(res,user._id.toString());return res.status(201).json({success:true,message:'Account created successfully',data:{user:publicUser(user)}});}catch(e){console.error('register',e);return res.status(500).json({success:false,message:'Unable to create account'});}}

export async function login(req:Request,res:Response){try{const parsed=loginSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,message:'Invalid login data',errors:parsed.error.issues});const user=await User.findOne({email:parsed.data.email.toLowerCase()}).select('+password');if(!user?.password||!(await bcrypt.compare(parsed.data.password,user.password)))return res.status(401).json({success:false,message:'Invalid email or password'});setAuthCookie(res,user._id.toString());return res.json({success:true,message:'Login successful',data:{user:publicUser(user)}});}catch(e){console.error('login',e);return res.status(500).json({success:false,message:'Unable to login'});}}

export async function googleLogin(req:Request,res:Response){try{const clientId=process.env.GOOGLE_CLIENT_ID;if(!clientId)return res.status(503).json({success:false,message:'Google sign-in is not configured on the server'});const credential=req.body?.credential;if(typeof credential!=='string'||!credential)return res.status(400).json({success:false,message:'Google credential is required'});const client=new OAuth2Client(clientId);const ticket=await client.verifyIdToken({idToken:credential,audience:clientId});const payload=ticket.getPayload();if(!payload?.sub||!payload.email)return res.status(401).json({success:false,message:'Invalid Google credential'});let user=await User.findOne({email:payload.email.toLowerCase()});if(!user){user=await User.create({name:payload.name||payload.email.split('@')[0],email:payload.email.toLowerCase(),googleId:payload.sub,avatar:payload.picture||''});}else if(!user.googleId){user.googleId=payload.sub;if(payload.picture&&!user.avatar)user.avatar=payload.picture;await user.save();}setAuthCookie(res,user._id.toString());return res.json({success:true,message:'Google sign-in successful',data:{user:publicUser(user)}});}catch(e){console.error('googleLogin',e);return res.status(401).json({success:false,message:'Google sign-in could not be verified'});}}

export async function logout(_req:Request,res:Response){res.clearCookie('token',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'});return res.json({success:true,message:'Logged out successfully'});}
export async function me(req:AuthenticatedRequest,res:Response){try{if(!req.user)return res.status(401).json({success:false,message:'Authentication required'});const user=await User.findById(req.user.userId);if(!user)return res.status(404).json({success:false,message:'User not found'});return res.json({success:true,data:{user:publicUser(user)}});}catch(e){console.error('me',e);return res.status(500).json({success:false,message:'Unable to retrieve user'});}}

export async function updateProfile(req:AuthenticatedRequest,res:Response){try{if(!req.user)return res.status(401).json({success:false,message:'Authentication required'});const name=typeof req.body?.name==='string'?req.body.name.trim():'';const avatar=typeof req.body?.avatar==='string'?req.body.avatar.trim():undefined;if(name.length<2||name.length>50)return res.status(400).json({success:false,message:'Name must be between 2 and 50 characters'});const user=await User.findByIdAndUpdate(req.user.userId,{name,...(avatar!==undefined?{avatar}:{})},{new:true,runValidators:true});if(!user)return res.status(404).json({success:false,message:'User not found'});return res.json({success:true,message:'Profile updated successfully',data:{user:publicUser(user)}});}catch(e){console.error('profile',e);return res.status(500).json({success:false,message:'Unable to update profile'});}}

export async function changePassword(req:AuthenticatedRequest,res:Response){try{if(!req.user)return res.status(401).json({success:false,message:'Authentication required'});const parsed=passwordSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,message:'Invalid password data',errors:parsed.error.issues});const user=await User.findById(req.user.userId).select('+password');if(!user)return res.status(404).json({success:false,message:'User not found'});if(!user.password)return res.status(400).json({success:false,message:'Password login is not enabled for this account'});if(!(await bcrypt.compare(parsed.data.currentPassword,user.password)))return res.status(401).json({success:false,message:'Current password is incorrect'});user.password=await bcrypt.hash(parsed.data.newPassword,12);await user.save();setAuthCookie(res,user._id.toString());return res.json({success:true,message:'Password changed successfully'});}catch(e){console.error('password',e);return res.status(500).json({success:false,message:'Unable to change password'});}}

export async function getPreferences(req:AuthenticatedRequest,res:Response){if(!req.user)return res.status(401).json({success:false,message:'Authentication required'});const user=await User.findById(req.user.userId);if(!user)return res.status(404).json({success:false,message:'User not found'});return res.json({success:true,data:{preferences:user.preferences}});}
export async function updatePreferences(req:AuthenticatedRequest,res:Response){if(!req.user)return res.status(401).json({success:false,message:'Authentication required'});const updates:any={};if(typeof req.body?.notifications==='boolean')updates['preferences.notifications']=req.body.notifications;if(['light','dark','system'].includes(req.body?.theme))updates['preferences.theme']=req.body.theme;const user=await User.findByIdAndUpdate(req.user.userId,{$set:updates},{new:true,runValidators:true});if(!user)return res.status(404).json({success:false,message:'User not found'});return res.json({success:true,message:'Preferences updated successfully',data:{preferences:user.preferences}});}
